color0 #40484c
color1 #ffb4ab
color2 #8ad0ee
color3 #b4cad5
color4 #c5c3ea
color5 #8ad0ee
color6 #b4cad5
color7 #dee3e6
color8 #8a9296
color9 #ffb4ab
color10 #8ad0ee
color11 #b4cad5
color12 #c5c3ea
color13 #8ad0ee
color14 #b4cad5
color15 #dee3e6

cursor                #dee3e6
cursor_text_color     #0f1417
background            #0f1417
foreground            #dee3e6
selection_foreground  #c0c8cc
selection_background  #40484c
active_border_color   #8ad0ee
inactive_border_color #40484c
url_color             #8ad0ee

active_tab_foreground   #003545
active_tab_background   #8ad0ee
inactive_tab_foreground #c0c8cc
inactive_tab_background #40484c
cursor_trail_color      #c0c8cc
