color0 #42474f
color1 #ffb4ab
color2 #9ccaff
color3 #b6c8e1
color4 #e9b4f7
color5 #9ccaff
color6 #b6c8e1
color7 #e1e2e7
color8 #8c919a
color9 #ffb4ab
color10 #9ccaff
color11 #b6c8e1
color12 #e9b4f7
color13 #9ccaff
color14 #b6c8e1
color15 #e1e2e7

cursor                #e1e2e7
cursor_text_color     #111417
background            #111417
foreground            #e1e2e7
selection_foreground  #c2c7d0
selection_background  #42474f
active_border_color   #9ccaff
inactive_border_color #42474f
url_color             #9ccaff

active_tab_foreground   #003257
active_tab_background   #9ccaff
inactive_tab_foreground #c2c7d0
inactive_tab_background #42474f
cursor_trail_color      #c2c7d0
