color0 #44483e
color1 #ffb4ab
color2 #aed18d
color3 #becbae
color4 #a0cfcd
color5 #aed18d
color6 #becbae
color7 #e2e3d9
color8 #8e9286
color9 #ffb4ab
color10 #aed18d
color11 #becbae
color12 #a0cfcd
color13 #aed18d
color14 #becbae
color15 #e2e3d9

cursor                #e2e3d9
cursor_text_color     #11140e
background            #11140e
foreground            #e2e3d9
selection_foreground  #c4c8ba
selection_background  #44483e
active_border_color   #aed18d
inactive_border_color #44483e
url_color             #aed18d

active_tab_foreground   #1c3703
active_tab_background   #aed18d
inactive_tab_foreground #c4c8ba
inactive_tab_background #44483e
cursor_trail_color      #c4c8ba
