# Sources
source=~/.config/mango/source/cursor.conf
source=~/.config/mango/source/bind.conf
source=~/.config/mango/source/rules.conf
source=~/.config/mango/source/looks.conf
source=~/.config/mango/source/animation.conf
source=~/.config/mango/source/layout.conf
source=~/.config/mango/source/auto-start.conf

source=/home/lemontree/.config/mango/noctalia.conf

# | Environment Variables |
# Set your environment variables here. | https://mangowm.github.io/docs/configuration/basics#environment-variables

env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORMTHEME_QT6,qt6ct
 #env = WLR_SCENE_DISABLE_DIRECT_SCANOUT,1
 #env = WLR_DRM_NO_ATOMIC,1
 #WLR_DRM_DEVICES=/dev/dri/card0:/dev/dri/card1 mango
 #WLR_DRM_DEVICES=/dev/dri/card0 mango
 #env = WLR_RENDERER,vulkan

# | Outputs Configuration |
# Configure your monitors here or in the DMS "Displays" settings. | https://mangowm.github.io/docs/configuration/monitors
# Run `wlr-randr` to get your monitors information.
# You will have to remove "#" and edit it for it to take effect.

#monitorrule = name:HEADLESS-4, width:3440, height:1440, refresh:180, x:0, y:0, rr:0, vrr:1
monitorrule = name:DP-1, width:3440, height:1440, refresh:180, x:0, y:0, vrr:0, rr:0, hdr:1
monitorrule = name:DP-2, width:2560, height:1440, refresh:59.951, x:3440, y:0, vrr:0, rr:0, hdr:1

hdr_depth = 2
allow_tearing = 2

# System & Hardware
https://mangowm.github.io/docs/configuration/miscellaneous#system--hardware

xwayland_persistence = 1
syncobj_enable = 1
allow_lock_transparent = 0
allow_shortcuts_inhibit = 1

# Focus & Input
https://mangowm.github.io/docs/configuration/miscellaneous#focus--input

focus_on_activate = 1
sloppyfocus = 1
warpcursor = 1
cursor_hide_timeout = 0
cursor_hide_on_keypress = 0
drag_tile_to_tile = 1
drag_tile_small = 0
drag_corner = 3
drag_warp_cursor = 1
axis_bind_apply_timeout = 100

# Multi-Monitor & Tags
https://mangowm.github.io/docs/configuration/miscellaneous#multi-monitor--tags

focus_cross_monitor = 1
exchange_cross_monitor = 1
focus_cross_tag = 1
view_current_to_back = 0
scratchpad_cross_monitor = 0
single_scratchpad = 1

# Snap
enable_floating_snap = 1
snap_distance = 100
no_border_when_single = 0
idleinhibit_ignore_visible = 0
tag_carousel = 0
drag_tile_refresh_interval = 8.0
drag_floating_refresh_interval = 8.0
