# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x11140eff
bordercolor = 0x8e9286ff
dropcolor = 0xaed18d80
splitcolor = 0xa0cfcdff
focuscolor = 0xaed18dff
maximizescreencolor = 0xbecbaeff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xa0cfcdff
globalcolor = 0x324e18ff
overlaycolor = 0x3f4a34ff
jump_label_decorate_fg_color = 0xe2e3d9ff
jump_label_decorate_bg_color = 0x282b24ff
jump_label_decorate_focus_fg_color = 0x1c3703ff
jump_label_decorate_focus_bg_color = 0xaed18dff
jump_label_decorate_border_color = 0x8e9286ff
group_bar_decorate_fg_color = 0xe2e3d9ff
group_bar_decorate_bg_color = 0x282b24ff
group_bar_decorate_focus_fg_color = 0x1c3703ff
group_bar_decorate_focus_bg_color = 0xaed18dff
group_bar_decorate_border_color = 0x8e9286ff
