# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x000000ff
rootcolor = 0x111318ff
bordercolor = 0x8e9099ff
dropcolor = 0xabc7ff80
splitcolor = 0xddbce0ff
focuscolor = 0xabc7ffff
maximizescreencolor = 0xbec6dcff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xddbce0ff
globalcolor = 0x294677ff
overlaycolor = 0x3e4759ff
jump_label_decorate_fg_color = 0xe2e2e9ff
jump_label_decorate_bg_color = 0x282a2fff
jump_label_decorate_focus_fg_color = 0x0c305fff
jump_label_decorate_focus_bg_color = 0xabc7ffff
jump_label_decorate_border_color = 0x8e9099ff
group_bar_decorate_fg_color = 0xe2e2e9ff
group_bar_decorate_bg_color = 0x282a2fff
group_bar_decorate_focus_fg_color = 0x0c305fff
group_bar_decorate_focus_bg_color = 0xabc7ffff
group_bar_decorate_border_color = 0x8e9099ff
