# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x000000ff
rootcolor = 0x14140cff
bordercolor = 0x929182ff
dropcolor = 0xc7cc7980
splitcolor = 0xa3d0bfff
focuscolor = 0xc7cc79ff
maximizescreencolor = 0xc8c9a6ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xa3d0bfff
globalcolor = 0x464a02ff
overlaycolor = 0x47482eff
jump_label_decorate_fg_color = 0xe5e3d6ff
jump_label_decorate_bg_color = 0x2a2a22ff
jump_label_decorate_focus_fg_color = 0x303300ff
jump_label_decorate_focus_bg_color = 0xc7cc79ff
jump_label_decorate_border_color = 0x929182ff
group_bar_decorate_fg_color = 0xe5e3d6ff
group_bar_decorate_bg_color = 0x2a2a22ff
group_bar_decorate_focus_fg_color = 0x303300ff
group_bar_decorate_focus_bg_color = 0xc7cc79ff
group_bar_decorate_border_color = 0x929182ff
