[Audio]
Volume=60

[General]
ColorScheme=Breeze Dark
FooterStyle=floating
GuiStyle=Breeze
LastPlayedFile=https://www.youtube.com/watch?v=
LastUrl=https://www.youtube.com/live/JBmzfJAyRNE?si=s3KkO737-JkRJ2-T
ShowHeader=false
ShowMenuBar=false
