[Audio]
Volume=60

[General]
ColorScheme=Breeze Dark
FooterStyle=floating
GuiStyle=Breeze
LastPlayedFile=file:///home/lemontree/Drive/4TB HDD/Raw footages/Replay_2026-09-09_06-15-03.mp4
LastUrl=https://www.youtube.com/live/JBmzfJAyRNE?si=s3KkO737-JkRJ2-T
ShowHeader=false
ShowMenuBar=false
