config_version = 14

[accessibility]
ui_scale = 1.2500000111758709

[audio]
enable_sounds = true
notification_sound = "/home/lemontree/Drive/4TB Drive/Sound effects/terminal_on.mp3"
sound_volume = 0.99999997764825821
volume_change_sound = "/home/lemontree/Drive/4TB Drive/Sound effects/Choosing.wav"

[bar]
order = [ "Bar" ]

    [bar.Bar]
    background_opacity = 0.0
    capsule = true
    capsule_border = "primary"
    capsule_opacity = 0.39999999105930328
    capsule_radius = 6
    center = []
    color = "primary"
    contact_shadow = false
    end = [ "workspaces", "recorder", "tray", "group:g2", "widget_2", "bar" ]
    font_weight = 700
    margin_edge = 0
    margin_ends = 0
    padding = 7
    scale = 2.0000000223517418
    start = [ "group:g1", "media", "active_window" ]
    thickness = 45
    widget_spacing = 2

        [bar.Bar.monitor.DP-2]
        end = []
        start = [ "group:g1", "RAM_CUSTOM", "group:g2", "VRAM", "UP", "DOWN" ]

            [[bar.Bar.monitor.DP-2.capsule_group]]
            accordion = false
            accordion_direction = "end"
            border = "#53EAFD"
            enabled = true
            fill = "surface_variant"
            id = "g1"
            members = [ "CPU_CUSTOM", "CPU_TEMP" ]
            opacity = 0.39999997615814209
            padding = 6.0
            radius = 6.0

            [[bar.Bar.monitor.DP-2.capsule_group]]
            accordion = false
            accordion_direction = "end"
            border = "#7BF1A8"
            enabled = true
            fill = "surface_variant"
            id = "g2"
            members = [ "GPU", "GPU_TEMP" ]
            opacity = 0.39999997615814209
            padding = 6.0
            radius = 6.0

        [[bar.Bar.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = "primary"
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "date", "clock" ]
        opacity = 0.40000000596046448
        padding = 6.0
        radius = 6.0
        widget_spacing = 7

        [[bar.Bar.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = "primary"
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "notifications", "bluetooth", "widget" ]
        opacity = 0.40000000596046448
        padding = 6.0
        radius = 6.0
        widget_spacing = 7

[control_center]
sidebar = "full"
sidebar_section = "full"

[desktop_widgets]
schema_version = 1
widget_order = []

    [desktop_widgets.grid]
    cell_size = 24
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
background_opacity = 0.0099999997764825821
border = "primary"
border_width = 4.0
enabled = false
icon_size = 64
launcher_custom_image = "/home/lemontree/Drive/4TB Drive/Avatar Cut Out/dibujo-24.png"
margin_edge = 2
monitors = [ "DP-1" ]
pinned = [
    "steam",
    "com.shellyorg.shelly",
    "brave-origin",
    "org.gnome.TextEditor",
    "proton-pass",
    "proton.vpn.app.gtk",
    "proton-mail",
    "com.ktechpit.ultimate-media-downloader",
    "org.cachyos.scx-manager",
    "org.cachyos.KernelManager",
    "localsend"
]
reserve_space = false
shadow = false
show_dots = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 900.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = false
    timeout = 660.0

[location]
address = "Chicago"

[lockscreen]
blur_intensity = 0.74999998323619366

[lockscreen_widgets]
enabled = true
schema_version = 1
widget_order = [
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-login-box@WL-1",
    "lockscreen-login-box@DP-2",
    "lockscreen-login-box@DP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 1720.0001220703125
    cy = 1317.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        center_password_text = false
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 720.0
    cx = 480.00009155273438
    cy = 1560.8890380859375
    output = "DP-2"
    placement_height = 2560.0
    placement_width = 1440.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        center_password_text = false
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1720.0
    cy = 1197.3333740234375
    output = "HDMI-A-1"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@WL-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 640.0
    cy = 597.0
    output = "WL-1"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@WL-1".settings]
        center_password_text = false
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 256.0
    box_width = 512.0
    cx = 312.00003051757812
    cy = 208.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = -0.0
    type = "clock"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 256.0
    box_width = 512.0
    cx = 3128.000244140625
    cy = 208.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        color = "#53EAFD"
        color2 = "#FFDF20"
        stat = "cpu_usage"
        stat2 = "ram_pct"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 256.0
    box_width = 512.0
    cx = 3128.000244140625
    cy = 528.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        color = "#7BF1A8"
        color2 = "#FFA1AD"
        stat = "gpu_usage"
        stat2 = "gpu_vram"

[notification]
background_opacity = 0.0099999997764825821
layer = "overlay"
monitors = [ "DP-1" ]
position = "top_left"
scale = 1.2500000111758709

[osd]
background_opacity = 0.0099999997764825821
scale = 1.25

    [osd.kinds]
    media = false

[plugin_settings."8bury/mini-docker"]
manager_layer = "overlay"

[plugin_settings."alexander/game-launcher"]
steampoacher_enabled = true

[plugin_settings."blackbartblues/audio-switcher"]
audio-switcher_placement = "floating"
audio-switcher_position = "center"

[plugin_settings."blackbartblues/keymap"]
compositor = "mangowc"
panel_layer = "overlay"

[plugin_settings."ezequiel/mango_layouts"]
list_mode = true
panel_layer = "overlay"
panel_position = "center"

[plugin_settings."joshuaslate/shelly"]
interval = 100

[plugin_settings."nightwatch75/file-search"]
panel_placement = "floating"
panel_position = "center"
show_hidden = true

[plugin_settings."noctalia/mpvpaper"]
auto_pause = false
picker_placement = "floating"
picker_position = "center"
video_directory = "/home/lemontree/Drive/4TB HDD/Music Visualizer"

[plugin_settings."noctalia/notes"]
panel_layer = "overlay"
panel_position = "top_left"

[plugin_settings."noctalia/screen_recorder"]
audio_source = "default_output"
directory = "/home/lemontree/Drive/4TB HDD/Raw footages"
quality = "medium"
replay_duration = 140
replay_enabled = true
video_codec = "av1"

[plugin_settings."noctalia/wallhaven"]
browser_placement = "floating"
browser_position = "center"

[plugin_settings."prponkshe/mango-displays"]
panel_layer = "overlay"
panel_placement = "floating"
panel_position = "center"

[plugins]
auto_update = "all"
enabled = [
    "noctalia/kaomoji",
    "yogaeru/mango_layout",
    "noctalia/notes",
    "oldirtty/color_picker",
    "8bury/mini-docker",
    "nightwatch75/file-search",
    "blackbartblues/keymap",
    "blackbartblues/audio-switcher",
    "ezequiel/mango_layouts",
    "noctalia/mpvpaper",
    "prponkshe/mango-displays"
]

    [[plugins.source]]
    auto_update = true
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    auto_update = true
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
avatar_path = "/home/lemontree/Drive/4TB Drive/Avatar Cut Out/lemon_tree_cutout.png"
font_family = "Noto Sans Mono"
lang = "en"
polkit_agent = true
settings_show_advanced = true
settings_window_translucent = true
ui_scale = 1.2500000111758709

    [shell.launcher]
    pinned = [
        "steam",
        "org.gnome.TextEditor",
        "com.shellyorg.shelly",
        "brave-origin",
        "proton-pass",
        "localsend",
        "org.gnome.Calculator",
        "org.cachyos.KernelManager",
        "org.cachyos.scx-manager",
        "heroic"
    ]

    [shell.panel]
    control_center_placement = "floating"
    control_center_position = "center"
    session_placement = "floating"
    session_position = "center"
    shadow = false
    transparency_mode = "glass"
    wallpaper_placement = "floating"
    wallpaper_position = "center"

    [shell.screenshot]
    directory = "/home/lemontree/Drive/4TB HDD/Screenshot"

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "suspend"
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    shortcut = "5"
    variant = "destructive"

    [[shell.session.actions]]
    action = "command"
    command = "systemctl reboot --firmware-setup"
    enabled = true
    glyph = "artboard"
    label = "UEFI"
    shortcut = "6"
    variant = "default"

    [[shell.session.actions]]
    action = "command"
    command = "killall mango"
    enabled = true
    glyph = "terminal-2"
    label = "TTY"
    shortcut = "7"
    variant = "default"

    [shell.shadow]
    alpha = 0.39999999105930328
    direction = "down_left"

[system.monitor]
gpu_poll_seconds = 2

[theme]
builtin = "Catppuccin"
community_palette = "Rose Pine Moon"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "cava", "foot", "gtk3", "gtk4", "kcolorscheme", "kitty", "mango", "qt" ]
    community_ids = [
        "tauon",
        "discord",
        "libreoffice",
        "micro",
        "neovim",
        "heroiclauncher",
        "steam",
        "fuzzel",
        "fastfetch",
        "obs",
        "hyprtoolkit",
        "papirus-icons",
        "yazi"
    ]

[wallpaper]
directory = "/home/lemontree/Drive/4TB Drive/Wallpaper"
transition_on_startup = true

    [wallpaper.automation]
    enabled = false
    order = "alphabetical"

    [wallpaper.default]
    path = "/home/lemontree/Drive/4TB Drive/Wallpaper/wallhaven-l3xlwq.jpg"

    [wallpaper.last]
    path = "/home/lemontree/Drive/4TB Drive/Wallpaper/wallhaven-l3xlwq.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/lemontree/Drive/4TB Drive/Wallpaper/wallhaven-l3xlwq.jpg"

    [wallpaper.monitors.DP-2]
    path = "/home/lemontree/Drive/4TB Drive/Wallpaper/wallhaven-l3xlwq.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/lemontree/Drive/4TB Drive/Wallpaper/wallhaven-6k38g7.jpg"

[widget.CLOCK_CUSTOM]
capsule = true
capsule_border = "#FFFFFF"
capsule_fill = "#FFFFFF"
capsule_foreground = "#FFFFFF"
capsule_opacity = 0.01
color = "#FFFFFF"
icon_color = "#FFFFFF"
type = "clock"

[widget.CPU_CUSTOM]
capsule = true
capsule_border = "#53EAFD"
capsule_fill = "#53EAFD"
capsule_foreground = "#53EAFD"
capsule_opacity = 0.01
color = "#53EAFD"
highlight_color = "#53EAFD"
icon_color = "#53EAFD"
type = "sysmon"

[widget.CPU_TEMP]
capsule = true
capsule_border = "#53EAFD"
capsule_fill = "#53EAFD"
capsule_foreground = "#53EAFD"
capsule_opacity = 0.01
color = "#53EAFD"
highlight_color = "#53EAFD"
icon_color = "#53EAFD"
stat = "cpu_temp"
type = "sysmon"

[widget.DOWN]
capsule = true
capsule_border = "#A3B3FF"
capsule_foreground = "#A3B3FF"
capsule_opacity = 0.40000000000000002
color = "#A3B3FF"
highlight_color = "#A3B3FF"
icon_color = "#A3B3FF"
stat = "net_rx"
type = "sysmon"

[widget.GPU]
capsule = true
capsule_border = "#7BF1A8"
capsule_fill = "#7BF1A8"
capsule_foreground = "#7BF1A8"
capsule_opacity = 0.01
color = "#7BF1A8"
highlight_color = "#7BF1A8"
icon_color = "#7BF1A8"
stat = "gpu_usage"
type = "sysmon"

[widget.GPU_TEMP]
capsule = true
capsule_border = "#7BF1A8"
capsule_fill = "#7BF1A8"
capsule_foreground = "#7BF1A8"
color = "#7BF1A8"
highlight_color = "#7BF1A8"
icon_color = "#7BF1A8"
stat = "gpu_temp"
type = "sysmon"

[widget.RAM_CUSTOM]
capsule = true
capsule_border = "#FFA1AD"
capsule_foreground = "#FFA1AD"
capsule_opacity = 0.40000000000000002
color = "#FFA1AD"
highlight_color = "#FFA1AD"
icon_color = "#FFA1AD"
stat = "ram_used"
type = "sysmon"

[widget.UP]
capsule = true
capsule_border = "#F4A8FF"
capsule_foreground = "#F4A8FF"
capsule_opacity = 0.40000000000000002
color = "#F4A8FF"
highlight_color = "#F4A8FF"
icon_color = "#F4A8FF"
stat = "net_tx"
type = "sysmon"

[widget.VRAM]
capsule = true
capsule_border = "#FFDF20"
capsule_foreground = "#FFDF20"
capsule_opacity = 0.40000000000000002
color = "#FFDF20"
highlight_color = "#FFDF20"
icon_color = "#FFDF20"
stat = "gpu_vram_used"
type = "sysmon"

[widget.active_window]
capsule = true
capsule_radius = 6
enabled = false
max_length = 800
min_length = 0
title_scroll = "always"

[widget.audio_visualizer]
bands = 128
capsule = true
capsule_radius = 6
high_color = "secondary"
show_when_idle = true
width = 300.0

[widget.bar]
type = "prponkshe/mango-displays:bar"

[widget.battery]
capsule = true
capsule_radius = 6

[widget.bluetooth]
capsule = true
capsule_radius = 6

[widget.bongocat]
script = "scripts/bongocat.lua"
type = "scripted"

[widget.brightness]
capsule = true
capsule_radius = 6

[widget.cat]
audio_spectrum = true
tappy_mode = true
type = "noctalia/bongocat:cat"

[widget.clock]
capsule = true
capsule_radius = 6

[widget.date]
capsule_opacity = 0.0
color = "primary"

[widget.media]
capsule = true
capsule_opacity = 0.40000000000000002
max_length = 800
min_length = 0
title_scroll = "always"

[widget.network]
capsule = true
capsule_radius = 6

[widget.notifications]
capsule = true
capsule_radius = 6

[widget.picker]
type = "yogaeru/mango_layout:picker"

[widget.picker_2]
type = "yogaeru/mango_layout:picker"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.screen_recorder]
script = "scripts/screen_recorder.lua"
type = "scripted"

[widget.sysmon]
capsule = true
capsule_border = "#7BF1A8"
capsule_fill = "#7BF1A8"
capsule_foreground = "#7BF1A8"
capsule_opacity = 0.01
capsule_radius = 6
color = "#7BF1A8"
highlight_color = "#016630"
icon_color = "#7BF1A8"
stat = "gpu_usage"

[widget.taskbar]
inactive_opacity = 0.75
show_all_outputs = true

[widget.tray]
capsule = true
capsule_radius = 6
detached_panel = true

[widget.wallpaper]
font_weight = 700

[widget.widget]
type = "oldirtty/color_picker:widget"

[widget.widget_2]
type = "blackbartblues/audio-switcher:widget"

[widget.workspaces]
capsule_radius = 6
hide_when_empty = true