# | Look n Feel |
# theming | https://mangowm.github.io/docs/visuals

#gappih = 20
#gappiv = 20
#gappoh = 40
#gappov = 40
#borderpx = 4
#border_radius = 10

border_radius=12
gappih=15
gappiv=15
gappoh=15
gappov=15
borderpx=5

#scratchpad_width_ratio = 0.8
#scratchpad_height_ratio = 0.9

scratchpad_width_ratio = 0.5
scratchpad_height_ratio = 0.75

#rootcolor = 0x201b14ff
#maximizescreencolor = 0x00000000
#scratchpadcolor = 0x516c93ff
#globalcolor = 0xffffffff
#overlaycolor = 0x14a57cff

#urgentcolor = 0xad401fff
#bordercolor = 0x1A9FFFFF
#focuscolor = 0xffeb3bff

blur = 1
blur_layer = 1
blur_optimized = 1
#blur_params_num_passes = 2
#blur_params_radius = 4
#blur_params_noise = 0.04
#blur_params_brightness = 0.9
#blur_params_contrast = 0.9
blur_params_saturation = 1.2

blur_params_num_passes = 3
blur_params_radius = 2
blur_params_noise = 0.05
blur_params_brightness = 0.9
blur_params_contrast = 0.9

shadows = 1
layer_shadows = 0
shadow_only_floating = 0
shadows_size = 12
shadows_blur = 15
shadows_position_x = 0
shadows_position_y = 0
shadowscolor = 0x000000ff

layerrule = noanim:1, noblur:1, layer_name:selection

#Overview Jump Mode

jump_label_decorate_border_width = 5
jump_label_decorate_corner_radius = 12
jump_label_decorate_padding_x = 10
jump_label_decorate_padding_y = 10
jump_label_decorate_font_desc = FantasqueSansM Nerd Font Bold 112

#Monocle Tab

group_bar_height = 50
group_bar_decorate_border_width = 5
group_bar_decorate_corner_radius = 12
group_bar_decorate_padding_x = 0
group_bar_decorate_padding_y = 0
tab_bar_decorate_font_desc = FantasqueSansM Nerd Font Bold 40

